name: kalanirbhar
description: AI-powered marketplace assistant for local artisans
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  audioplayers: ^5.2.1
  speech_to_text: ^6.6.0
  image_picker: ^1.0.4
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.6
  animate_do: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  
  # State Management
  provider: ^6.1.1
  
  # Charts for Analytics (Windows compatible)
  fl_chart: ^0.66.0
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Utils
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  
  # Image Processing (basic)
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true